version: "3.7"

services:
  pdat_monkey:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./prisma:/home/node/app/prisma
    container_name: pdat_monkey
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: yarn start:dev
